url: "https://adityayadavalli1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "aditya yadavalli" # the name of your site, e.g. ACME Corp.
description: "Graduate Student at IIIT-H"
